### PR TITLE
Add Windows Build

### PR DESCRIPTION
**Pull request by gyuha**
Added build for Windows.

```
npm run packWin
```

Build it by typing above.

### CODE REVIEW

**Comment by uyu423** [comment]
This is very good feature !! I also thought we needed this feature.
I have some idea. if you reference `process.platfrom` variable, you can specific platform (`win32` or `drawin`) 
If you reference this variable, you can merge `packWin.js` and `pack.js`
What do you think of this idea?

- ref. https://nodejs.org/api/process.html#process_process_platform

**Comment by ZzMark** [comment]
package.json need some fix.

in windows, `run build`  rm has not support. window need to use `del`

if can add some dependency, replace `rm` with `rimraf` to build


if not, some fix:
```js
"buildWin": "del /F /S /Q dist && webpack",
"packWin": "set NODE_ENV=production && npm run buildWin && node bin/packWin.js"
```

**Comment by ZzMark** [comment]
emmm....

some feature can't support for windows.

like help -> Learn More
image

not yet bug for main feature.

**Comment by uyu423** [comment]
@ZzMark Good point. For environment variables, it is better to use `cross-env` rather than `set`.

And I tested `help -> Learn More` function and it doesn't work on MacOS. I wonder if there is a problem with the original source code.

**Pull request closed without merging**
